[project]
name        = "apa"
version     = "0.1.0"
description = "Async Prompt Application powered by LiteLLM"
dependencies = [
    "litellm>=1.24.0"
]
requires-python = ">=3.13"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
apa = "main:main"
